// Do not edit this file; automatically generated.

/* eslint-disable */
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) { // AMD
    define(["./blockly_compressed.js"], factory);
  } else if (typeof exports === 'object') { // Node.js
    module.exports = factory(require("./blockly_compressed.js"));
  } else { // Script
    root.lua = factory(root.Blockly);
    root.Blockly.Lua = root.lua.luaGenerator;
  }
}(this, function(__parent__) {
var $=__parent__.__namespace__;
var qs=function(a,b,c){return b==="FIRST"?"1":b==="FROM_END"?"#"+a+" + 1 - "+c:b==="LAST"?"#"+a:b==="RANDOM"?"math.random(#"+a+")":c},rs=function(a,b){var c=0,d="";b.STATEMENT_PREFIX&&(d+=b.injectId(b.STATEMENT_PREFIX,a));do{let e=b.valueToCode(a,"IF"+c,X.NONE)||"false",f=b.statementToCode(a,"DO"+c);b.STATEMENT_SUFFIX&&(f=b.prefixLines(b.injectId(b.STATEMENT_SUFFIX,a),b.INDENT)+f);d+=(c>0?"else":"")+"if "+e+" then\n"+f;c++}while(a.getInput("IF"+c));if(a.getInput("ELSE")||b.STATEMENT_SUFFIX)c=a.getInput("ELSE")?
b.statementToCode(a,"ELSE"):"",b.STATEMENT_SUFFIX&&(c=b.prefixLines(b.injectId(b.STATEMENT_SUFFIX,a),b.INDENT)+c),d+="else\n"+c;return d+"end\n"},ss=function(a,b){return a.includes("goto continue\n")?a+b+"::continue::\n":a},ts=function(a,b){var c=a.getField("TIMES")?String(Number(a.getFieldValue("TIMES"))):b.valueToCode(a,"TIMES",X.NONE)||"0";c=$.yf(c)?parseInt(c,10):"math.floor("+c+")";var d=b.statementToCode(a,"DO");d=b.addLoopTrap(d,a);d=ss(d,b.INDENT);return"for "+b.nameDB_.getDistinctName("count",
$.P.VARIABLE)+" = 1, "+c+" do\n"+d+"end\n"},us=function(a,b){var c=a.getFieldValue("OP");if(c==="NEG")return a=b.valueToCode(a,"NUM",X.UNARY)||"0",["-"+a,X.UNARY];if(c==="POW10")return a=b.valueToCode(a,"NUM",X.EXPONENTIATION)||"0",["10 ^ "+a,X.EXPONENTIATION];a=c==="ROUND"?b.valueToCode(a,"NUM",X.ADDITIVE)||"0":b.valueToCode(a,"NUM",X.NONE)||"0";switch(c){case "ABS":c="math.abs("+a+")";break;case "ROOT":c="math.sqrt("+a+")";break;case "LN":c="math.log("+a+")";break;case "LOG10":c="math.log("+a+", 10)";
break;case "EXP":c="math.exp("+a+")";break;case "ROUND":c="math.floor("+a+" + .5)";break;case "ROUNDUP":c="math.ceil("+a+")";break;case "ROUNDDOWN":c="math.floor("+a+")";break;case "SIN":c="math.sin(math.rad("+a+"))";break;case "COS":c="math.cos(math.rad("+a+"))";break;case "TAN":c="math.tan(math.rad("+a+"))";break;case "ASIN":c="math.deg(math.asin("+a+"))";break;case "ACOS":c="math.deg(math.acos("+a+"))";break;case "ATAN":c="math.deg(math.atan("+a+"))";break;default:throw Error("Unknown math operator: "+
c);}return[c,X.HIGH]},vs=function(a,b){var c=b.getProcedureName(a.getFieldValue("NAME")),d="";b.STATEMENT_PREFIX&&(d+=b.injectId(b.STATEMENT_PREFIX,a));b.STATEMENT_SUFFIX&&(d+=b.injectId(b.STATEMENT_SUFFIX,a));d&&(d=b.prefixLines(d,b.INDENT));var e="";b.INFINITE_LOOP_TRAP&&(e=b.prefixLines(b.injectId(b.INFINITE_LOOP_TRAP,a),b.INDENT));var f="";a.getInput("STACK")&&(f=b.statementToCode(a,"STACK"));var g="";a.getInput("RETURN")&&(g=b.valueToCode(a,"RETURN",X.NONE)||"");var h="";f&&g&&(h=d);g?g=b.INDENT+
"return "+g+"\n":f||(f="");var m=[],z=a.getVarModels();for(let E=0;E<z.length;E++)m[E]=b.getVariableName(z[E].getId());d="function "+c+"("+m.join(", ")+")\n"+d+e+f+h+g+"end\n";d=b.scrub_(a,d);b.definitions_["%"+c]=d;return null},ws=function(a,b){var c=a.getField("TEXT")?b.quote_(a.getFieldValue("TEXT")):b.valueToCode(a,"TEXT",X.NONE)||"''";b=b.provideFunction_("text_prompt",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(msg)
  io.write(msg)
  io.flush()
  return io.read()
end
`)+"("+c+")";a.getFieldValue("TYPE")==="NUMBER"&&(b="tonumber("+b+", 10)");return[b,X.HIGH]},ys=function(a,b){return[b.getVariableName(a.getFieldValue("VAR")),X.ATOMIC]},zs=function(a,b){var c=b.valueToCode(a,"VALUE",X.NONE)||"0";return b.getVariableName(a.getFieldValue("VAR"))+" = "+c+"\n"},X,As=X||(X={});As[As.ATOMIC=0]="ATOMIC";As[As.HIGH=1]="HIGH";As[As.EXPONENTIATION=2]="EXPONENTIATION";As[As.UNARY=3]="UNARY";As[As.MULTIPLICATIVE=4]="MULTIPLICATIVE";As[As.ADDITIVE=5]="ADDITIVE";
As[As.CONCATENATION=6]="CONCATENATION";As[As.RELATIONAL=7]="RELATIONAL";As[As.AND=8]="AND";As[As.OR=9]="OR";As[As.NONE=99]="NONE";
var Bs=class extends $.Rp{constructor(a="Lua"){super(a);this.isInitialized=!1;for(let b in X)a=X[b],typeof a!=="string"&&(this["ORDER_"+b]=a);this.addReservedWords("_,__inext,assert,bit,colors,colours,coroutine,disk,dofile,error,fs,fetfenv,getmetatable,gps,help,io,ipairs,keys,loadfile,loadstring,math,native,next,os,paintutils,pairs,parallel,pcall,peripheral,print,printError,rawequal,rawget,rawset,read,rednet,redstone,rs,select,setfenv,setmetatable,sleep,string,table,term,textutils,tonumber,tostring,turtle,type,unpack,vector,write,xpcall,_VERSION,__indext,HTTP,and,break,do,else,elseif,end,false,for,function,if,in,local,nil,not,or,repeat,return,then,true,until,while,add,sub,mul,div,mod,pow,unm,concat,len,eq,lt,le,index,newindex,call,assert,collectgarbage,dofile,error,_G,getmetatable,inpairs,load,loadfile,next,pairs,pcall,print,rawequal,rawget,rawlen,rawset,select,setmetatable,tonumber,tostring,type,_VERSION,xpcall,require,package,string,table,math,bit32,io,file,os,debug")}init(a){super.init(a);this.nameDB_?
this.nameDB_.reset():this.nameDB_=new $.jj(this.RESERVED_WORDS_);this.nameDB_.setVariableMap(a.getVariableMap());this.nameDB_.populateVariables(a);this.nameDB_.populateProcedures(a);this.isInitialized=!0}finish(a){var b=Object.values(this.definitions_);a=super.finish(a);this.isInitialized=!1;this.nameDB_.reset();return b.join("\n\n")+"\n\n\n"+a}scrubNakedValue(a){return"local _ = "+a+"\n"}quote_(a){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\\n").replace(/'/g,"\\'");return"'"+a+"'"}multiline_quote_(a){return a.split(/\n/g).map(this.quote_).join(" .. '\\n' ..\n")}scrub_(a,
b,c=!1){var d="";if(!a.outputConnection||!a.outputConnection.targetConnection){var e=a.getCommentText();e&&(e=$.xf(e,this.COMMENT_WRAP-3),d+=this.prefixLines(e,"-- ")+"\n");for(let f=0;f<a.inputList.length;f++)a.inputList[f].type===$.ie.VALUE&&(e=a.inputList[f].connection.targetBlock())&&(e=this.allNestedComments(e))&&(d+=this.prefixLines(e,"-- "))}a=a.nextConnection&&a.nextConnection.targetBlock();c=c?"":this.blockToCode(a);return d+b+c}};var Cs={};Cs.controls_if=rs;Cs.controls_ifelse=rs;Cs.logic_boolean=function(a){return[a.getFieldValue("BOOL")==="TRUE"?"true":"false",X.ATOMIC]};Cs.logic_compare=function(a,b){var c={EQ:"==",NEQ:"~=",LT:"<",LTE:"<=",GT:">",GTE:">="}[a.getFieldValue("OP")],d=b.valueToCode(a,"A",X.RELATIONAL)||"0";a=b.valueToCode(a,"B",X.RELATIONAL)||"0";return[d+" "+c+" "+a,X.RELATIONAL]};Cs.logic_negate=function(a,b){return["not "+(b.valueToCode(a,"BOOL",X.UNARY)||"true"),X.UNARY]};
Cs.logic_null=function(){return["nil",X.ATOMIC]};Cs.logic_operation=function(a,b){var c=a.getFieldValue("OP")==="AND"?"and":"or",d=c==="and"?X.AND:X.OR,e=b.valueToCode(a,"A",d);a=b.valueToCode(a,"B",d);e||a?(b=c==="and"?"true":"false",e||(e=b),a||(a=b)):a=e="false";return[e+" "+c+" "+a,d]};Cs.logic_ternary=function(a,b){var c=b.valueToCode(a,"IF",X.AND)||"false",d=b.valueToCode(a,"THEN",X.AND)||"nil";a=b.valueToCode(a,"ELSE",X.OR)||"nil";return[c+" and "+d+" or "+a,X.OR]};var Ds={controls_flow_statements:function(a,b){var c="";b.STATEMENT_PREFIX&&(c+=b.injectId(b.STATEMENT_PREFIX,a));b.STATEMENT_SUFFIX&&(c+=b.injectId(b.STATEMENT_SUFFIX,a));if(b.STATEMENT_PREFIX){let d=a.getSurroundLoop();d&&!d.suppressPrefixSuffix&&(c+=b.injectId(b.STATEMENT_PREFIX,d))}switch(a.getFieldValue("FLOW")){case "BREAK":return c+"break\n";case "CONTINUE":return c+"goto continue\n"}throw Error("Unknown flow statement.");},controls_for:function(a,b){var c=b.getVariableName(a.getFieldValue("VAR")),
d=b.valueToCode(a,"FROM",X.NONE)||"0",e=b.valueToCode(a,"TO",X.NONE)||"0",f=b.valueToCode(a,"BY",X.NONE)||"1",g=b.statementToCode(a,"DO");g=b.addLoopTrap(g,a);g=ss(g,b.INDENT);a="";if($.yf(d)&&$.yf(e)&&$.yf(f))var h=(Number(d)<=Number(e)?"":"-")+Math.abs(Number(f));else a="",h=b.nameDB_.getDistinctName(c+"_inc",$.P.VARIABLE),a+=h+" = ",a=$.yf(f)?a+(Math.abs(f)+"\n"):a+("math.abs("+f+")\n"),a=a+("if ("+d+") > ("+e+") then\n")+(b.INDENT+h+" = -"+h+"\n"),a+="end\n";return a+("for "+c+" = "+d+", "+e+
", "+h)+(" do\n"+g+"end\n")},controls_forEach:function(a,b){var c=b.getVariableName(a.getFieldValue("VAR")),d=b.valueToCode(a,"LIST",X.NONE)||"{}",e=b.statementToCode(a,"DO");e=b.addLoopTrap(e,a);e=ss(e,b.INDENT);return"for _, "+c+" in ipairs("+d+") do \n"+e+"end\n"}};Ds.controls_repeat=ts;Ds.controls_repeat_ext=ts;
Ds.controls_whileUntil=function(a,b){var c=a.getFieldValue("MODE")==="UNTIL",d=b.valueToCode(a,"BOOL",c?X.UNARY:X.NONE)||"false",e=b.statementToCode(a,"DO");e=b.addLoopTrap(e,a);e=ss(e,b.INDENT);c&&(d="not "+d);return"while "+d+" do\n"+e+"end\n"};var Es={math_arithmetic:function(a,b){var c={ADD:[" + ",X.ADDITIVE],MINUS:[" - ",X.ADDITIVE],MULTIPLY:[" * ",X.MULTIPLICATIVE],DIVIDE:[" / ",X.MULTIPLICATIVE],POWER:[" ^ ",X.EXPONENTIATION]}[a.getFieldValue("OP")],d=c[0];c=c[1];var e=b.valueToCode(a,"A",c)||"0";a=b.valueToCode(a,"B",c)||"0";return[e+d+a,c]},math_atan2:function(a,b){var c=b.valueToCode(a,"X",X.NONE)||"0";return["math.deg(math.atan2("+(b.valueToCode(a,"Y",X.NONE)||"0")+", "+c+"))",X.HIGH]},math_change:function(a,b){var c=b.valueToCode(a,
"DELTA",X.ADDITIVE)||"0";a=b.getVariableName(a.getFieldValue("VAR"));return a+" = "+a+" + "+c+"\n"},math_constant:function(a){return{PI:["math.pi",X.HIGH],E:["math.exp(1)",X.HIGH],GOLDEN_RATIO:["(1 + math.sqrt(5)) / 2",X.MULTIPLICATIVE],SQRT2:["math.sqrt(2)",X.HIGH],SQRT1_2:["math.sqrt(1 / 2)",X.HIGH],INFINITY:["math.huge",X.HIGH]}[a.getFieldValue("CONSTANT")]},math_constrain:function(a,b){var c=b.valueToCode(a,"VALUE",X.NONE)||"0",d=b.valueToCode(a,"LOW",X.NONE)||"-math.huge";a=b.valueToCode(a,"HIGH",
X.NONE)||"math.huge";return["math.min(math.max("+c+", "+d+"), "+a+")",X.HIGH]},math_modulo:function(a,b){var c=b.valueToCode(a,"DIVIDEND",X.MULTIPLICATIVE)||"0";a=b.valueToCode(a,"DIVISOR",X.MULTIPLICATIVE)||"0";return[c+" % "+a,X.MULTIPLICATIVE]},math_number:function(a){a=Number(a.getFieldValue("NUM"));return[String(a),a<0?X.UNARY:X.ATOMIC]},math_number_property:function(a,b){var c={EVEN:[" % 2 == 0",X.MULTIPLICATIVE,X.RELATIONAL],ODD:[" % 2 == 1",X.MULTIPLICATIVE,X.RELATIONAL],WHOLE:[" % 1 == 0",
X.MULTIPLICATIVE,X.RELATIONAL],POSITIVE:[" > 0",X.RELATIONAL,X.RELATIONAL],NEGATIVE:[" < 0",X.RELATIONAL,X.RELATIONAL],DIVISIBLE_BY:[null,X.MULTIPLICATIVE,X.RELATIONAL],PRIME:[null,X.NONE,X.HIGH]},d=a.getFieldValue("PROPERTY"),[e,f,g]=c[d];c=b.valueToCode(a,"NUMBER_TO_CHECK",f)||"0";if(d==="PRIME")a=b.provideFunction_("math_isPrime",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(n)
  -- https://en.wikipedia.org/wiki/Primality_test#Naive_methods
  if n == 2 or n == 3 then
    return true
  end
  -- False if n is NaN, negative, is 1, or not whole.
  -- And false if n is divisible by 2 or 3.
  if not(n > 1) or n % 1 ~= 0 or n % 2 == 0 or n % 3 == 0 then
    return false
  end
  -- Check all the numbers of form 6k +/- 1, up to sqrt(n).
  for x = 6, math.sqrt(n) + 1.5, 6 do
    if n % (x - 1) == 0 or n % (x + 1) == 0 then
      return false
    end
  end
  return true
end
`)+"("+c+")";else if(d==="DIVISIBLE_BY"){a=b.valueToCode(a,"DIVISOR",X.MULTIPLICATIVE)||"0";if(a==="0")return["nil",X.ATOMIC];a=c+" % "+a+" == 0"}else a=c+e;return[a,g]},math_on_list:function(a,b){function c(){return b.provideFunction_("math_sum",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  local result = 0
  for _, v in ipairs(t) do
    result = result + v
  end
  return result
end
`)}var d=a.getFieldValue("OP");a=b.valueToCode(a,"LIST",X.NONE)||"{}";switch(d){case "SUM":d=c();break;case "MIN":d=b.provideFunction_("math_min",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  if #t == 0 then
    return 0
  end
  local result = math.huge
  for _, v in ipairs(t) do
    if v < result then
      result = v
    end
  end
  return result
end
`);break;case "AVERAGE":d=b.provideFunction_("math_average",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  if #t == 0 then
    return 0
  end
  return ${c()}(t) / #t
end
`);break;case "MAX":d=b.provideFunction_("math_max",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  if #t == 0 then
    return 0
  end
  local result = -math.huge
  for _, v in ipairs(t) do
    if v > result then
      result = v
    end
  end
  return result
end
`);break;case "MEDIAN":d=b.provideFunction_("math_median",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  -- Source: http://lua-users.org/wiki/SimpleStats
  if #t == 0 then
    return 0
  end
  local temp = {}
  for _, v in ipairs(t) do
    if type(v) == 'number' then
      table.insert(temp, v)
    end
  end
  table.sort(temp)
  if #temp % 2 == 0 then
    return (temp[#temp / 2] + temp[(#temp / 2) + 1]) / 2
  else
    return temp[math.ceil(#temp / 2)]
  end
end
`);break;case "MODE":d=b.provideFunction_("math_modes",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  -- Source: http://lua-users.org/wiki/SimpleStats
  local counts = {}
  for _, v in ipairs(t) do
    if counts[v] == nil then
      counts[v] = 1
    else
      counts[v] = counts[v] + 1
    end
  end
  local biggestCount = 0
  for _, v  in pairs(counts) do
    if v > biggestCount then
      biggestCount = v
    end
  end
  local temp = {}
  for k, v in pairs(counts) do
    if v == biggestCount then
      table.insert(temp, k)
    end
  end
  return temp
end
`);break;case "STD_DEV":d=b.provideFunction_("math_standard_deviation",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  local m
  local vm
  local total = 0
  local count = 0
  local result
  m = #t == 0 and 0 or ${c()}(t) / #t
  for _, v in ipairs(t) do
    if type(v) == 'number' then
      vm = v - m
      total = total + (vm * vm)
      count = count + 1
    end
  end
  result = math.sqrt(total / (count-1))
  return result
end
`);break;case "RANDOM":d=b.provideFunction_("math_random_list",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t)
  if #t == 0 then
    return nil
  end
  return t[math.random(#t)]
end
`);break;default:throw Error("Unknown operator: "+d);}return[d+"("+a+")",X.HIGH]},math_random_float:function(){return["math.random()",X.HIGH]},math_random_int:function(a,b){var c=b.valueToCode(a,"FROM",X.NONE)||"0";a=b.valueToCode(a,"TO",X.NONE)||"0";return["math.random("+c+", "+a+")",X.HIGH]}};Es.math_round=us;Es.math_single=us;Es.math_trig=us;var Fs={procedures_callnoreturn:function(a,b){return b.forBlock.procedures_callreturn(a,b)[0]+"\n"},procedures_callreturn:function(a,b){var c=b.getProcedureName(a.getFieldValue("NAME")),d=[],e=a.getVarModels();for(let f=0;f<e.length;f++)d[f]=b.valueToCode(a,"ARG"+f,X.NONE)||"nil";return[c+"("+d.join(", ")+")",X.HIGH]}};Fs.procedures_defnoreturn=vs;Fs.procedures_defreturn=vs;
Fs.procedures_ifreturn=function(a,b){var c="if "+(b.valueToCode(a,"CONDITION",X.NONE)||"false")+" then\n";b.STATEMENT_SUFFIX&&(c+=b.prefixLines(b.injectId(b.STATEMENT_SUFFIX,a),b.INDENT));a.hasReturnValue_?(a=b.valueToCode(a,"VALUE",X.NONE)||"nil",c+=b.INDENT+"return "+a+"\n"):c+=b.INDENT+"return\n";return c+"end\n"};var Gs={text:function(a,b){return[b.quote_(a.getFieldValue("TEXT")),X.ATOMIC]},text_append:function(a,b){var c=b.getVariableName(a.getFieldValue("VAR"));a=b.valueToCode(a,"TEXT",X.CONCATENATION)||"''";return c+" = "+c+" .. "+a+"\n"},text_changeCase:function(a,b){var c=a.getFieldValue("CASE");a=b.valueToCode(a,"TEXT",X.NONE)||"''";var d;c==="UPPERCASE"?d="string.upper":c==="LOWERCASE"?d="string.lower":c==="TITLECASE"&&(d=b.provideFunction_("text_titlecase",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(str)
  local buf = {}
  local inWord = false
  for i = 1, #str do
    local c = string.sub(str, i, i)
    if inWord then
      table.insert(buf, string.lower(c))
      if string.find(c, "%s") then
        inWord = false
      end
    else
      table.insert(buf, string.upper(c))
      inWord = true
    end
  end
  return table.concat(buf)
end
`));return[d+"("+a+")",X.HIGH]},text_charAt:function(a,b){var c=a.getFieldValue("WHERE")||"FROM_START",d=b.valueToCode(a,"VALUE",X.NONE)||"''";if(c==="RANDOM")b=b.provideFunction_("text_random_letter",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(str)
  local index = math.random(string.len(str))
  return string.sub(str, index, index)
end
`)+"("+d+")";else{if(c==="FIRST")c="1";else if(c==="LAST")c="-1";else if(a=b.valueToCode(a,"AT",c==="FROM_END"?X.UNARY:X.NONE)||"1",c==="FROM_START")c=a;else if(c==="FROM_END")c="-"+a;else throw Error("Unhandled option (text_charAt).");b=c.match(/^-?\w*$/)?"string.sub("+d+", "+c+", "+c+")":b.provideFunction_("text_char_at",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(str, index)
  return string.sub(str, index, index)
end
`)+"("+d+", "+c+")"}return[b,X.HIGH]},text_count:function(a,b){var c=b.valueToCode(a,"TEXT",X.NONE)||"''";a=b.valueToCode(a,"SUB",X.NONE)||"''";return[b.provideFunction_("text_count",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(haystack, needle)
  if #needle == 0 then
    return #haystack + 1
  end
  local i = 1
  local count = 0
  while true do
    i = string.find(haystack, needle, i, true)
    if i == nil then
      break
    end
    count = count + 1
    i = i + #needle
  end
  return count
end
`)+"("+c+", "+a+")",X.HIGH]},text_getSubstring:function(a,b){var c=b.valueToCode(a,"STRING",X.NONE)||"''",d=a.getFieldValue("WHERE1"),e=b.valueToCode(a,"AT1",d==="FROM_END"?X.UNARY:X.NONE)||"1";if(d==="FIRST")d=1;else if(d==="FROM_START")d=e;else if(d==="FROM_END")d="-"+e;else throw Error("Unhandled option (text_getSubstring)");e=a.getFieldValue("WHERE2");a=b.valueToCode(a,"AT2",e==="FROM_END"?X.UNARY:X.NONE)||"1";if(e==="LAST")a=-1;else if(e!=="FROM_START")if(e==="FROM_END")a="-"+a;else throw Error("Unhandled option (text_getSubstring)");
return["string.sub("+c+", "+d+", "+a+")",X.HIGH]},text_indexOf:function(a,b){var c=b.valueToCode(a,"FIND",X.NONE)||"''",d=b.valueToCode(a,"VALUE",X.NONE)||"''";return[(a.getFieldValue("END")==="FIRST"?b.provideFunction_("firstIndexOf",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(str, substr)
  local i = string.find(str, substr, 1, true)
  if i == nil then
    return 0
  end
  return i
end
`):b.provideFunction_("lastIndexOf",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(str, substr)
  local i = string.find(string.reverse(str), string.reverse(substr), 1, true)
  if i then
    return #str + 2 - i - #substr
  end
  return 0
end
`))+"("+d+", "+c+")",X.HIGH]},text_isEmpty:function(a,b){return["#"+(b.valueToCode(a,"VALUE",X.UNARY)||"''")+" == 0",X.RELATIONAL]},text_join:function(a,b){if(a.itemCount_===0)return["''",X.ATOMIC];if(a.itemCount_===1)return["tostring("+(b.valueToCode(a,"ADD0",X.NONE)||"''")+")",X.HIGH];if(a.itemCount_===2){var c=b.valueToCode(a,"ADD0",X.CONCATENATION)||"''";a=b.valueToCode(a,"ADD1",X.CONCATENATION)||"''";return[c+" .. "+a,X.CONCATENATION]}c=[];for(let d=0;d<a.itemCount_;d++)c[d]=b.valueToCode(a,
"ADD"+d,X.NONE)||"''";return["table.concat({"+c.join(", ")+"})",X.HIGH]},text_length:function(a,b){return["#"+(b.valueToCode(a,"VALUE",X.UNARY)||"''"),X.UNARY]},text_print:function(a,b){return"print("+(b.valueToCode(a,"TEXT",X.NONE)||"''")+")\n"}};Gs.text_prompt=ws;Gs.text_prompt_ext=ws;Gs.text_replace=function(a,b){var c=b.valueToCode(a,"TEXT",X.NONE)||"''",d=b.valueToCode(a,"FROM",X.NONE)||"''";a=b.valueToCode(a,"TO",X.NONE)||"''";return[b.provideFunction_("text_replace",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(haystack, needle, replacement)
  local buf = {}
  local i = 1
  while i <= #haystack do
    if string.sub(haystack, i, i + #needle - 1) == needle then
      for j = 1, #replacement do
        table.insert(buf, string.sub(replacement, j, j))
      end
      i = i + #needle
    else
      table.insert(buf, string.sub(haystack, i, i))
      i = i + 1
    end
  end
  return table.concat(buf)
end
`)+"("+c+", "+d+", "+a+")",X.HIGH]};Gs.text_reverse=function(a,b){return["string.reverse("+(b.valueToCode(a,"TEXT",X.NONE)||"''")+")",X.HIGH]};Gs.text_trim=function(a,b){var c={LEFT:"^%s*(,-)",RIGHT:"(.-)%s*$",BOTH:"^%s*(.-)%s*$"}[a.getFieldValue("MODE")];return["string.gsub("+(b.valueToCode(a,"TEXT",X.NONE)||"''")+', "'+c+'", "%1")',X.HIGH]};var Hs={};Hs.variables_get=ys;Hs.variables_set=zs;var Is={};Is.variables_get_dynamic=ys;Is.variables_set_dynamic=zs;var Js=new Bs,Ks=Object.assign({},{lists_create_empty:function(){return["{}",X.HIGH]},lists_create_with:function(a,b){var c=Array(a.itemCount_);for(let d=0;d<a.itemCount_;d++)c[d]=b.valueToCode(a,"ADD"+d,X.NONE)||"nil";return["{"+c.join(", ")+"}",X.HIGH]},lists_getIndex:function(a,b){var c=a.getFieldValue("MODE")||"GET",d=a.getFieldValue("WHERE")||"FROM_START",e=b.valueToCode(a,"VALUE",X.HIGH)||"({})";if(d!=="LAST"&&d!=="FROM_END"&&d!=="RANDOM"||e.match(/^\w+$/)){b=b.valueToCode(a,"AT",c==="GET"&&
d==="FROM_END"?X.ADDITIVE:X.NONE)||"1";b=qs(e,d,b);if(c==="GET")return[e+"["+b+"]",X.HIGH];d="table.remove("+e+", "+b+")";return c==="GET_REMOVE"?[d,X.HIGH]:d+"\n"}if(c==="REMOVE")return c=b.valueToCode(a,"AT",d==="FROM_END"?X.ADDITIVE:X.NONE)||"1",b=b.nameDB_.getDistinctName("tmp_list",$.P.VARIABLE),c=qs(b,d,c),b+" = "+e+"\ntable.remove("+b+", "+c+")\n";a=b.valueToCode(a,"AT",X.NONE)||"1";return[(c==="GET"?b.provideFunction_("list_get_"+d.toLowerCase(),["function "+b.FUNCTION_NAME_PLACEHOLDER_+"(t"+
(d==="FROM_END"||d==="FROM_START"?", at)":")"),"  return t["+qs("t",d,"at")+"]","end"]):b.provideFunction_("list_remove_"+d.toLowerCase(),["function "+b.FUNCTION_NAME_PLACEHOLDER_+"(t"+(d==="FROM_END"||d==="FROM_START"?", at)":")"),"  return table.remove(t, "+qs("t",d,"at")+")","end"]))+"("+e+(d==="FROM_END"||d==="FROM_START"?", "+a:"")+")",X.HIGH]},lists_getSublist:function(a,b){var c=b.valueToCode(a,"LIST",X.NONE)||"{}",d=a.getFieldValue("WHERE1"),e=a.getFieldValue("WHERE2"),f=b.valueToCode(a,"AT1",
X.NONE)||"1";a=b.valueToCode(a,"AT2",X.NONE)||"1";var g=d==="FROM_END"||d==="FROM_START"?", at1":"",h=e==="FROM_END"||e==="FROM_START"?", at2":"";return[b.provideFunction_("list_sublist_"+d.toLowerCase()+"_"+e.toLowerCase(),`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(source${g}${h})
  local t = {}
  local start = ${qs("source",d,"at1")}
  local finish = ${qs("source",e,"at2")}
  for i = start, finish do
    table.insert(t, source[i])
  end
  return t
end
`)+"("+c+(d==="FROM_END"||d==="FROM_START"?", "+f:"")+(e==="FROM_END"||e==="FROM_START"?", "+a:"")+")",X.HIGH]},lists_indexOf:function(a,b){var c=b.valueToCode(a,"FIND",X.NONE)||"''",d=b.valueToCode(a,"VALUE",X.NONE)||"{}";return[(a.getFieldValue("END")==="FIRST"?b.provideFunction_("first_index",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t, elem)
  for k, v in ipairs(t) do
    if v == elem then
      return k
    end
  end
  return 0
end
`):b.provideFunction_("last_index",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(t, elem)
  for i = #t, 1, -1 do
    if t[i] == elem then
      return i
    end
  end
  return 0
end
`))+"("+d+", "+c+")",X.HIGH]},lists_isEmpty:function(a,b){return["#"+(b.valueToCode(a,"VALUE",X.UNARY)||"{}")+" == 0",X.RELATIONAL]},lists_length:function(a,b){return["#"+(b.valueToCode(a,"VALUE",X.UNARY)||"{}"),X.UNARY]},lists_repeat:function(a,b){var c=b.provideFunction_("create_list_repeated",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(item, count)
  local t = {}
  for i = 1, count do
    table.insert(t, item)
  end
  return t
end
  `),d=b.valueToCode(a,"ITEM",X.NONE)||"nil";a=b.valueToCode(a,"NUM",X.NONE)||"0";return[c+"("+d+", "+a+")",X.HIGH]},lists_reverse:function(a,b){a=b.valueToCode(a,"LIST",X.NONE)||"{}";return[b.provideFunction_("list_reverse",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(input)
  local reversed = {}
  for i = #input, 1, -1 do
    table.insert(reversed, input[i])
  end
  return reversed
end
`)+"("+a+")",X.HIGH]},lists_setIndex:function(a,b){var c=b.valueToCode(a,"LIST",X.HIGH)||"{}",d=a.getFieldValue("MODE")||"SET",e=a.getFieldValue("WHERE")||"FROM_START",f=b.valueToCode(a,"AT",X.ADDITIVE)||"1";a=b.valueToCode(a,"TO",X.NONE)||"Nil";var g="";e!=="LAST"&&e!=="FROM_END"&&e!=="RANDOM"||c.match(/^\w+$/)||(b=b.nameDB_.getDistinctName("tmp_list",$.P.VARIABLE),g=b+" = "+c+"\n",c=b);g=d==="SET"?g+(c+"["+qs(c,e,f)+"] = "+a):g+("table.insert("+c+", "+(qs(c,e,f)+(e==="LAST"?" + 1":""))+", "+a+")");
return g+"\n"},lists_sort:function(a,b){var c=b.valueToCode(a,"LIST",X.NONE)||"{}",d=a.getFieldValue("DIRECTION")==="1"?1:-1;a=a.getFieldValue("TYPE");return[b.provideFunction_("list_sort",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(list, typev, direction)
  local t = {}
  for n,v in pairs(list) do table.insert(t, v) end
  local compareFuncs = {
    NUMERIC = function(a, b)
      return (tonumber(tostring(a)) or 0)
          < (tonumber(tostring(b)) or 0) end,
    TEXT = function(a, b)
      return tostring(a) < tostring(b) end,
    IGNORE_CASE = function(a, b)
      return string.lower(tostring(a)) < string.lower(tostring(b)) end
  }
  local compareTemp = compareFuncs[typev]
  local compare = compareTemp
  if direction == -1
  then compare = function(a, b) return compareTemp(b, a) end
  end
  table.sort(t, compare)
  return t
end
`)+"("+c+',"'+a+'", '+d+")",X.HIGH]},lists_split:function(a,b){var c=b.valueToCode(a,"INPUT",X.NONE),d=b.valueToCode(a,"DELIM",X.NONE)||"''";a=a.getFieldValue("MODE");if(a==="SPLIT")c||(c="''"),b=b.provideFunction_("list_string_split",`
function ${b.FUNCTION_NAME_PLACEHOLDER_}(input, delim)
  local t = {}
  local pos = 1
  while true do
    next_delim = string.find(input, delim, pos)
    if next_delim == nil then
      table.insert(t, string.sub(input, pos))
      break
    else
      table.insert(t, string.sub(input, pos, next_delim-1))
      pos = next_delim + #delim
    end
  end
  return t
end
`);else if(a==="JOIN")c||(c="{}"),b="table.concat";else throw Error("Unknown mode: "+a);return[b+"("+c+", "+d+")",X.HIGH]}},Cs,Ds,Es,Fs,Gs,Hs,Is);for(let a in Ks)Js.forBlock[a]=Ks[a];var Ls={};Ls.LuaGenerator=Bs;Ls.Order=X;Ls.luaGenerator=Js;$.__chunk_lua=Ls;
$.__chunk_lua.__namespace__=$;
return $.__chunk_lua;
}));


//# sourceMappingURL=lua_compressed.js.map
